# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850b1b7d45296b0c065d9ae2b15652fc59daa9a845639dc16950b3c65b085ef048ba23f4e1df4b66aad102b0f924de39ebd302ca2fa4c1fa8f8af4ad11ceefe1

test:
  secret_key_base: 2f30248c19f74b63c36452012aeb2a1fc4deefdbdc5cbcdd99ad69785213d28e1cf578dd7a0c408c9f7582d2a81494dd15728302b73e3c27956b4e37cdd21253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
